### ISSUE TITLE
Possibility to process single file

### ISSUE THREAD

**Issue by alpipego** [SassNinja/postcss-extract-media-query#1]
Scenario: I don't want to extract the media queries of (lazy-loaded) component-specific css, I only want to do this on my main stylesheet. Is this possible? Thanks.

**Comment by SassNinja** [comment]
@alpipego thanks for using this plugin and the feature request.

I'm not sure if I understood you correctly.
Would you provide more details regarding your project setup?
Is the component specific CSS defined in separate files?

If so I'd suggest to work over your build process to limit this PostCSS plugin to your main file only.

**Comment by alpipego** [comment]
Thanks for your reply. This was a typical case of looking at the trees without seeing the woods. Instead of globbing all files in a dir, I now have a separate (grunt) PostCSS task that only runs on the main file (as you suggested).

Thanks for making this plugin. It's exactly what I was looking for 💯🔥
