### ISSUE TITLE
extractAll not working

### ISSUE THREAD

**Issue by bnmlynx** [SassNinja/postcss-extract-media-query#12]
Hey, 

I'm trying to only extract media queries for one size, but I can't seem to get the extractAll option to work. 

Using your gulp example as a starting point here is my postcss.config.js

![image](https://user-images.githubusercontent.com/21080721/67754966-3f110e00-fa2f-11e9-9c70-314af80cae6f.png)

I'm still getting an example-screen-and-min-width-px.css

![image](https://user-images.githubusercontent.com/21080721/67755072-6667db00-fa2f-11e9-88f0-40d814266091.png)

Any help would be much appreciated, awesome plugin btw!

**Comment by SassNinja** [comment]
hi @bnmlynx 

you've use the gulp example without modification, haven't you?

I've just noticed I didn't update the package.json file of the examples meaning they all refer to an older version of the plugin without `extractAll` support

I'll update it asap!

**Comment by SassNinja** [comment]
ok, done!

https://github.com/SassNinja/postcss-extract-media-query/tree/master/examples/gulp

you can fix this easily yourself by running
`npm install postcss-extract-media-query@latest --save-dev`

apart from that I spotted an error in the gulpfile: `deleteMatch: true` was missing in the options
https://github.com/SassNinja/postcss-extract-media-query/blob/master/examples/gulp/gulpfile.js#L10

afterwards everything works correctly in this example

**Comment by bnmlynx** [comment]
Amazing!

Thank you very much for your speedy reply and fix!
