### ISSUE TITLE
Keep the media in same file

### ISSUE THREAD

**Issue by Faisal-Manzer** [SassNinja/postcss-extract-media-query#24]
I am using Preact with custom `postcss.config.js`. I want my styles to stay in same file or in the same output (inline CSS). How to do that.

**Comment by Faisal-Manzer** [comment]
Sorry. There was a new plugin by @SassNinja itself which does this greatly. https://github.com/SassNinja/postcss-combine-media-query combines all the media queries, this was what I needed.

**Comment by SassNinja** [comment]
glad to here my other plugin has solved your issue =)

btw I'll be mandatory for this job in future anyway as I'm going to remove the `combine` option in the next major release
