### ISSUE TITLE
Can this be used to only combine media queries?

### ISSUE THREAD

**Issue by qodesmith** [SassNinja/postcss-extract-media-query#7]
I see that this plugin is able to combine similar media queries. Is there a way to **_only_** use this feature **_without_** extracting the queries to their own file?

I used to use the [mq-packer](https://github.com/hail2u/node-css-mqpacker) plugin for postcss to combine similar media queries. Unfortunately that plugin is deprecated and no longer maintained.

**Comment by SassNinja** [comment]
Hi @qodesmith 

as the name points out this plugin is supposed to extract something, not reorder or rather merge only.

However you'll get your desired result when you set `output.path` to `null`
